import type { Metadata } from "next";
import "./globals.css";
import Header from "@/src/compoments/modules/header/Header";
import Footer from "@/src/compoments/modules/footer/Footer";

export const metadata: Metadata = {
  title: "MOZART",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/hvdtrial-graphit"
          rel="stylesheet"
        />
      </head>
      <body className={`antialiased max-w-360 mx-auto`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
